# Titre ou première chose à voir sur le site Web
title: Loïc Stéphane M. BAMENOU

# Photo de profil à rajouter 


# Description du poste ou du profil 
description: 

# Offrir la possibilité à une personne de récupérer mon code 
show_downloads: true 

# Thème à proposer pour notre site web
theme: jekyll-theme-minimal
