# Titre ou première chose à voir sur le site Web
title: Loïc Stéphane M. BAMENOU

# Photo de profil à rajouter 
logo: /Images/Photo_Pro/Photo.png

# Description du poste ou du profil 
description: Passionate Data Analyst BI with expertise in Power BI, Tableau, Python, and SQL. Currently at TDF, I optimize operational data and create interactive dashboards

# Offrir la possibilité à une personne de récupérer mon code 
show_downloads: false 

# Thème à proposer pour notre site web
theme: jekyll-theme-minimal
